#! /bin/bash

(
  cd ~/Projects/qmk_firmware ;
  make ergodox_ez:yuleugim ;
  echo -e "\033[0;33mLoading firmware. Please reset keyboard.." ;
  teensy_loader_cli -mmcu=atmega32u4 -w ergodox_ez_yuleugim.hex ;
  rm ergodox_ez_yuleugim.hex
)

